# PUNTO i: Archivo de configuración del cliente de chat RMI
# Contiene la dirección IP y el puerto del Name Server (rmiRegistry)
# Modifique estos valores según su entorno de red

# Dirección IP donde se encuentra el rmiRegistry (Name Server)
# Cambiar si el servidor está en otra máquina (ej: 192.168.1.10)
ns.ip=localhost

# Puerto por el cual escucha el rmiRegistry
ns.puerto=8080